"""Immutable NovelAI / 闲云 endpoints and provider ids."""

from __future__ import annotations

API_BASE = "https://api.novelai.net"
IMAGE_API_BASE = "https://image.novelai.net"
XIANYUN_API_BASE = "https://api.idlecloud.cc/api"
PROVIDER_NOVELAI = "novelai"
PROVIDER_XIANYUN = "xianyun"
PROVIDER_UNKNOWN = "unknown"
DIRECTOR_RESPONSE_MAX_BYTES = 96 * 1024 * 1024
DIRECTOR_ZIP_MAX_ENTRIES = 16
DIRECTOR_OUTPUT_MAX_BYTES = 48 * 1024 * 1024
DIRECTOR_OUTPUT_MAX_PIXELS = 64_000_000
_COOLDOWN_SEC = 3.0
_XIANYUN_COOLDOWN_SEC = 20.0
_TOKEN_ENTRIES_CACHE_TTL = 5.0
_XIANYUN_POLL_INTERVAL_SEC = 2.0
_XIANYUN_TIMEOUT_SEC = 240.0
_TOKEN_FAILURE_TTL_SEC = 600.0
_NAI_TRANSIENT_TTL_SEC = 15.0
_TRANSIENT_PROVIDER_TTL_SEC = 45.0
_TOKEN_FAILURE_LIMIT = 2
